export const siteConfig = {
  name: "Boby Maulana - Software Engineer",
  authorName: "Boby Maulana",
  username: "boby177",
  description:
    "Boby Maulana - Software Engineer specializing in backend and full-stack development. Explore my projects, experience, and skills across Node.js, Next.js, PHP and more.",
  url: "https://boby-ms.com",
  links: {
    github: "https://github.com/boby177",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "https://boby-ms.com/og-image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Boby Maulana",
    "Software Engineer",
    "Backend Developer",
    "Full Stack Developer",
    "Node.js Developer",
    "NestJS Developer",
    "Next.js Developer",
    "React Developer",
    "TypeScript",
    "SQL Server",
    "PostgreSQL",
    "PHP Developer",
    "CodeIgniter",
    "Web Developer",
    "Software Development",
    "Tech Portfolio",
    "Indonesia Software Engineer",
  ],
};
